baseurl: http://simonmika.com/
languageCode: en-us
title: "Simon says"
theme: hugo-theme-html5
MetaDataFormat: yaml
params:
  Description: "truths, opinions and preconceptions"
  Logotype: "img/logotype.svg"
  CSS:
    - "css/text.css"
    - "css/color.css"
    - "css/layout.css"
    - "css/form.css"
  ListMode: "title"
  FrontPageMode: "title"
  FrontPageSection: "article"
  NavigationInHeader: true
googleAnalytics: "UA-83177710-2"
paginate: 5
menu:
  main:
    - name: "Articles"
      weight: 10
      URL: "/"
